import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/header/Header";
import CartProvider from "@/Components/context _ to all/CartContext";
import { Toaster } from "react-hot-toast";
import ClientLayout from "@/Components/context _ to all/ClientLayout"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${dmSans.variable} h-full antialiased no-scrollbar`}
    >
      <body className="w-[80%] m-auto mt-30">
        <CartProvider>   {/* to TopHeader & Product Components (Cart page )*/}
          <Header />

          <Toaster position="bottom-right" toastOptions={{
            style: {
              background: '#e9e9e9',
              borderRadius: '5px',
              padding: '14px'
            }
          }}>
          </Toaster>

          <ClientLayout>
            {children}
          </ClientLayout>

        </CartProvider>
      </body>
    </html>
  );
}
